### ISSUE TITLE
SMD-Desktop

### ISSUE THREAD

**Issue by Mojas84** [noahweasley/SMD-Desktop#1]
Hi thanks for this application but on your site i cant download program.........:[

**Comment by noahweasley** [comment]
Hey, thank you for wanting to use S.M.D. The application is actually still in development. The site is finished but The desktop app is still in development for now. I am currently working on the project now. Please exercise patience

**Comment by noahweasley** [comment]
Thank you for wanting to download this app. I have released one version of the app. But there are lots of bugs currently in that version and I am looking to fix all bugs and improve the app. Go to the release page to download the application

**Comment by noahweasley** [comment]
Thank you for wanting to download S.M.D Dekstop. I have released one
version of the app. But there are lots of bugs currently in that version
and I am looking to fix all bugs and improve the app. Go to the download
page
<https://noahweasley.github.io/SMD-Desktop/website/pages/downloads/downloads.html>
to download the application. Cheers





Best Regards,
Ebenmelu Ifechukwu <https://www.linkedin.com/in/ebenmelu-ifechukwu>
