### ISSUE TITLE
 i cant download program.

### ISSUE THREAD

**Issue by KENPOKASMMA1982** [noahweasley/SMD-Desktop#2]
i cant download program.

**Comment by noahweasley** [comment]
Yes, I'm aware of that. Although I'm done with the website, the application is still in production

**Comment by noahweasley** [comment]
Thank you for wanting to download this app. I have released one version of the app. But there are lots of bugs currently in that version and I am looking to fix all bugs and improve the app. Go to release page to download the application

**Comment by noahweasley** [comment]
Thank you for wanting to download S.M.D Dekstop. I have released one
version of the app. But there are lots of bugs currently in that version
and I am looking to fix all bugs and improve the app. Go to the download
page
<https://noahweasley.github.io/SMD-Desktop/website/pages/downloads/downloads.html>
to download the application. Cheers





Best Regards,
Ebenmelu Ifechukwu <https://www.linkedin.com/in/ebenmelu-ifechukwu>
